# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: jagordapp'
  inputs:
    azureSubscription: 'ca-jagord-demo-test (f9b5da45-54cc-42d3-a58b-87adf6ad27ad)'
    appType: webAppLinux
    appName: jagordapp
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
