apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "aksdemojagord-8bce"
    labels:
        app: "aksdemojagord-8bce"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "aksdemojagord-8bce"
