apiVersion: v1
kind: Service
metadata:
    name: "jayaksdemo-8abb"
    labels:
        app: "jayaksdemo-8abb"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jayaksdemo-8abb"
