on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrjagord.azurecr.io
        username: ${{ secrets.acr_acrjagord_username }}
        password: ${{ secrets.acr_acrjagord_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrjagord.azurecr.io/aksdemojagord:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrjagord.azurecr.io/aksdemojagord:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemojagord_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksdemojagordb59b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksdemojagordb59b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksdemojagordb59b
        container-registry-url: acrjagord.azurecr.io
        container-registry-username: ${{ secrets.acr_acrjagord_username }}
        container-registry-password: ${{ secrets.acr_acrjagord_password }}
        secret-name: aksdemojagordockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksdemojagordb59b
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          acrjagord.azurecr.io/aksdemojagord:${{ github.sha }}
        imagepullsecrets: |
          aksdemojagordockerauth
